### ISSUE TITLE
Documentation about README_OAUTH.md

### ISSUE THREAD

**Issue by koyan** [AtakamaLLC/cloudsync#299]
In the readme, in the examples, we can read
```
# Get a generic client_id and client_secret. Do not use this in production code.
# For more information on getting your own client_id and client_secret, see README_OAUTH.md
```
But I have trouble locating the README_OAUTH.md . Could you point to it? 
Thanks

**Comment by howufiger7** [comment]
README_OAUTH.md is definitely missing, we'll need to update our docs in the near future.

For the time being, take a look at:
- https://atakama-llc-cloudsync.readthedocs-hosted.com/en/latest/oauth.html
- https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/msa-oauth?view=odsp-graph-online
- https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/app-registration?view=odsp-graph-online
