### ISSUE TITLE
request for a google_drive example with token save/refresh

### ISSUE THREAD

**Issue by magowiz** [AtakamaLLC/cloudsync#372]
Hi,
I was using directly google libraries to connect to my google drive account in my application, so I already have credentials provided by google, I wish to use cloudsync inside a project to sync gdrive with local folder, using cloudsync I can run the example provided and I also read the oauth part of documentation so I replaced generic_oauth with a proper one that uses mine credentials (app_id, app_secret), the problem is that every time I launch my code I have to perform oauth2 authentication, with browser and choosing account, consent to authorizations, so my code is not storing the token, I would like to know how to store and re-use/refresh token.

Here it is mine "pure" google drive code that works as I expected (but no cloudsync features):
```
from googleapiclient.discovery import build
from googleapiclient.http import (MediaFileUpload, MediaIoBaseDownload,  HttpError)
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google.auth.exceptions import RefreshError

def __token_handle__(self):
        """handles authentication token"""
        scopes = ['https://www.googleapis.com/auth/drive']
        creds = None
        if os.path.isfile(self.token_file):
            creds = Credentials.from_authorized_user_file(self.token_file, scopes)
        if not creds or not creds.valid:
            if creds and creds.expired and creds.refresh_token:
                try:
                    creds.refresh(Request())
                except RefreshError:
                    return None
            else:
                flow = InstalledAppFlow.from_client_secrets_file(self.credentials_file, scopes)
                creds = flow.run_local_server(port=0)
            with open(self.token_file, 'w') as token:
                token.write(creds.to_json())
        return creds

def __init__(self):
        self.token_file = os.path.join('secrets', 'token.json')
        self.credentials_file = os.path.join('secrets', 'credentials.json')
        self.signed_in = False
        creds = self.__token_handle__()
        if creds is None:
            return
        self.service = build('drive', 'v3', credentials=creds)
        self.signed_in = True
```
here it is cloudsync code I wrote using example and documentation about oauth (authorization every time):
```
        cred_path = os.path.join('secrets', 'credentials.json')
        with open(cred_path, 'r') as cred_file:
            cred_json = cred_file.read()
        self.creds = json.loads(cred_json)
        self.app_id = self.creds['installed']['client_id']
        self.app_secret = self.creds['installed']['client_secret']
        oauth_config = cloudsync.oauth.OAuthConfig(app_id=self.app_id, app_secret=self.app_secret)
        self.provider = cloudsync.create_provider('gdrive',  oauth_config=oauth_config)
        creds_auth = self.provider.authenticate()
        self.provider.connect(creds_auth)
```
this is not a bug report, probably I didn't understand how to use cloudsync, I reported also google drive "pure" code only to better explain what's my purpose.
Thanks in advance

**Comment by howufiger7** [comment]
This line is responsible for launching the browser for oauth:

`creds_auth = self.provider.authenticate()`

If you already have the creds you need, you can omit this line and pass your stored creds into `self.provider.connect()` instead.

Hope that helps.

**Comment by magowiz** [comment]
> This line is responsible for launching the browser for oauth:
> 
> `creds_auth = self.provider.authenticate()`
> 
> If you already have the creds you need, you can omit this line and pass your stored creds into `self.provider.connect()` instead.
> 
> Hope that helps.

Yes, you definitely pointed me to right path, I altered a bit mine cloudsync-using code and it worked like expected, thank you very much!
Now the part that connects it is different:
```
        # right after the create_provider instruction
        # if no token file authenticate as before but saving creds into new token
        if not os.path.isfile(self.token_file):
            creds_auth = self.provider.authenticate()
            with open(self.token_file, "w") as tkf:
                tkf.write(json.dumps(creds_auth))
         # if token file exist, parse the json and use it as creds
        else:
            with open(self.token_file, "r") as tkf:
                creds_auth = json.load(tkf)
        # in any of above cases, use creds_auth to connect
        self.provider.connect(creds_auth)
```
