### ISSUE TITLE
Refresh token not being returned for G-Drive?

### ISSUE THREAD

**Issue by pingusix** [AtakamaLLC/cloudsync#390]
Hi I'm currently implementing a client that downloads files from G-drive and Onedrive. Using the generic_oauth_config function it works fine for both and also works for Onedrive specifying my own cloudsync.oauth.OAuthConfig(app_id=clientid, app_secret=clientsecret,  port_range=portrange, host_name=hostname) with a access and refresh token being generated correctly on browser authentication and everything downloading as expected.

For G-Drive, once I get the creds back there doesn't seem to be a refresh token passed back resulting in a 'acquire a token using authenticate() first' error. 

I feel as though I'm missing a step as the generic_oauth_config works fine. 
Any help greatly appreciated

**Comment by earthman1** [comment]
Are you using the values provided in `cloudsync/command/utils.py` in `OAUTH_CONFIG["gdrive"]` for the `app_id` and `app_secret`, or are you sending your own?

**Comment by pingusix** [comment]
I was using my own but substituting in those from utils.py works correctly and I get a pair of tokens. 

There is a difference though, if I run with those from utils.py I am prompted for the user to reauthenticate every time I request a document on the google verification screen. If I run with mine, it asks the first time and then for subsequent visits it just  puts up 'oauth-successful' and comes back only with an access token.

It has to be something to do with the way I set up the app at the google end but I can't figure it out -I'll have a dig around, but at least it isn't a code issue by the look of it -all very strange. 

Cheers
Ed
